# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Also show dotnet when there is a solution file in the directory
[dotnet]
detect_extensions = ["csproj", "sln"]

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
