[manager]
layout         = [ 1, 3, 4 ]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
show_hidden    = true
show_symlink   = true

[preview]
tab_size   = 2
max_width  = 600
max_height = 900
cache_dir  = ""

[opener]
folder = [
	{ run = 'open -R "$@"', display_name = "Reveal in Finder" },
	{ run = '$EDITOR "$@"' },
]
archive = [
	{ run = 'unar "$1"', display_name = "Extract here" },
]
text = [
	{ run = '$EDITOR "$@"', block = true },
	{ run = 'alacritty -e bash -c "$EDITOR $@"' },
]
image = [
	{ run = 'brave "$@"', display_name = "Open in browser" },
	{ run = 'open "$@"', display_name = "Open" },
]
video = [
	{ run = 'mpv "$@"' },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" },
]
audio = [
	{ run = 'mpv "$@"', block = true, display_name = "open in mpv" },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" },
]
fallback = [
	{ run = 'open "$@"', display_name = "Open" },
	{ run = 'open -R "$@"', display_name = "Reveal in Finder" },
]

[open]
rules = [
	{ name = "*/", use = "folder" },

	{ mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "video" },
	{ mime = "audio/*", use = "audio" },
	{ mime = "inode/x-empty", use = "text" },

	{ mime = "application/json", use = "text" },
	{ mime = "*/javascript", use = "text" },

	{ mime = "application/zip", use = "archive" },
	{ mime = "application/gzip", use = "archive" },
	{ mime = "application/x-tar", use = "archive" },
	{ mime = "application/x-bzip", use = "archive" },
	{ mime = "application/x-bzip2", use = "archive" },
	{ mime = "application/x-7z-compressed", use = "archive" },
	{ mime = "application/x-rar", use = "archive" },

	{ mime = "*", use = "fallback" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false
