theme = "mydark"

[editor]
mouse = false
color-modes = true
completion-trigger-len = 1      # min-lenght to start auto-completion

[keys.normal]
"j"    = "move_char_left"
"k"    = "move_line_down"
"l"    = "move_line_up"
";"    = "move_char_right"
"A-;"  = "goto_next_buffer"
"A-j"  = "goto_previous_buffer"
"A-q"  = ":buffer-close"
"G"    = "goto_file_end"

[keys.select]
"j"    = "extend_char_left"
"k"    = "extend_line_down"
"l"    = "extend_line_up"
";"    = "extend_char_right"
