theme = "mydark"

[editor]
mouse = false
color-modes = true
completion-trigger-len = 1      # min-lenght to start auto-completion

[keys.normal]
"A-l"  = ":buffer-next"
"A-h"  = ":buffer-previous"
"A-q"  = ":buffer-close"
"G"    = ":g 99999999"
