# TODO: this broke after new helix version
# [[language]]
# name = "c-sharp"
# language-server = { command = "omnisharp", args = [ "--languageserver" ] }
[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}
