# My version of the onedark theme from: https://github.com/helix-editor/helix/blob/master/runtime/themes/onedark.toml
# Author : Gokul Soumya <gokulps15@gmail.com>

"namespace" = { fg = "white" }
"module" = { fg = "white" }

"type" = { fg = "green" }
"type.enum.variant" = { fg = "green1" }
# "constructor" = { fg = "type" }
# "variable.other.member" = { fg = "variable" }

"keyword" = { fg = "blue" }
"keyword.directive" = { fg = "blue" }
# "keyword.control" = { fg = "special" }
"label" = { fg = "blue" }
"tag" = "blue"

"special" = { fg = "white" }
"operator" = { fg = "white" }

"punctuation" = { fg = "white" }
"punctuation.delimiter" = { fg = "white" }

"variable" = { fg = "white" }
"variable.parameter" = { fg = "white" }
"variable.builtin" = { fg = "blue" }
"constant" = { fg = "white" }
"constant.builtin" = { fg = "blue" }

"function" = { fg = "yellow" }
"function.builtin" = { fg = "yellow" }
"function.macro" = { fg = "yellow" }
"attribute" = { fg = "yellow" }

"comment" = { fg = "light-gray", modifiers = ["italic"] }

"string" = { fg = "orange" }
"constant.character" = { fg = "orange" }
# "string.regexp" = { fg = "gold" }
# "constant.numeric" = { fg = "pale_green" }
"constant.character.escape" = { fg = "gold" }

"markup.heading" = { fg = "red" }
"markup.raw.inline" = { fg = "green" }
"markup.bold" = { fg = "gold", modifiers = ["bold"] }
"markup.italic" = { fg = "purple", modifiers = ["italic"] }
"markup.list" = { fg = "red" }
"markup.quote" = { fg = "yellow" }
"markup.link.url" = { fg = "cyan", modifiers = ["underlined"]}
"markup.link.text" = { fg = "purple" }

"diff.plus" = "green"
"diff.delta" = "gold"
"diff.minus" = "red"

diagnostic = { modifiers = ["underlined"] }
"info" = { fg = "blue", modifiers = ["bold"] }
"hint" = { fg = "green", modifiers = ["bold"] }
"warning" = { fg = "yellow", modifiers = ["bold"] }
"error" = { fg = "red", modifiers = ["bold"] }

"ui.background" = { bg = "black" }
"ui.virtual" = { fg = "faint-gray" }
"ui.virtual.indent-guide" = { fg = "faint-gray" }
"ui.virtual.whitespace" = { fg = "light-gray" }
"ui.virtual.ruler" = { bg = "gray" }

"ui.cursor" = { fg = "white", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "white", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "blue", modifiers = ["underlined"]}

"ui.selection" = { bg = "light-gray" }
"ui.selection.primary" = { bg = "gray" }
"ui.cursorline.primary" = { bg = "light-black" }

"ui.linenr" = { fg = "linenr" }
"ui.linenr.selected" = { fg = "white" }

"ui.statusline" = { fg = "white", bg = "light-black" }
"ui.statusline.inactive" = { fg = "light-gray", bg = "light-black" }
"ui.statusline.normal" = { fg = "light-black", bg = "blue" }
"ui.statusline.insert" = { fg = "light-black", bg = "green" }
"ui.statusline.select" = { fg = "light-black", bg = "purple" }

"ui.text" = { fg = "white" }
"ui.text.focus" = { fg = "white", bg = "light-black", modifiers = ["bold"] }

"ui.help" = { fg = "white", bg = "gray" }
"ui.popup" = { bg = "gray" }
"ui.window" = { fg = "gray" }
"ui.menu" = { fg = "white", bg = "gray" }
"ui.menu.selected" = { fg = "black", bg = "blue" }
"ui.menu.scroll" = { fg = "white", bg = "light-gray" }

[palette]

background = "#1E1E1E"
comment = "#608B4E"
variable = "#9CDCFE"
keyword = "#C586C0"
number = "#B5CEA8"
constant = "#B4CEA8"
bool = "#569CD6"
string = "#D69D85"


yellow = "#E5C07B"
blue = "#61AFEF"
red = "#E06C75"
purple = "#C678DD"
green = "#98C379"
green1 = "#4EC9B0"
gold = "#D19A66"
cyan = "#56B6C2"
white = "#ABB2BF"
black = "#282C34"
light-black = "#2C323C"
gray = "#3E4452"
faint-gray = "#3B4048"
light-gray = "#5C6370"
linenr = "#4B5263"

orange = "#ce9178"
