# My version of the onedark theme from: https://github.com/helix-editor/helix/blob/master/runtime/themes/onedark.toml

# Theme - UI
"ui.background" = { bg = "#1E2129" }
"ui.virtual" = { fg = "faint-gray" }
"ui.virtual.indent-guide" = { fg = "faint-gray" }
"ui.virtual.whitespace" = { fg = "light-gray" }
"ui.virtual.ruler" = { bg = "gray" }

"ui.cursor" = { fg = "greywhite", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "greywhite", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "blue", modifiers = ["underlined"]}

"ui.selection" = { bg = "light-gray" }
"ui.selection.primary" = { bg = "gray" }
"ui.cursorline.primary" = { bg = "light-black" }

"ui.linenr" = { fg = "#4B5263" }
"ui.linenr.selected" = { fg = "greywhite" }

"ui.statusline" = { fg = "greywhite", bg = "light-black" }
"ui.statusline.inactive" = { fg = "light-gray", bg = "light-black" }
"ui.statusline.normal" = { fg = "light-black", bg = "blue" }
"ui.statusline.insert" = { fg = "light-black", bg = "green" }
"ui.statusline.select" = { fg = "light-black", bg = "purple" }

"ui.text" = { fg = "greywhite" }
"ui.text.focus" = { fg = "greywhite", bg = "light-black", modifiers = ["bold"] }

"ui.help" = { fg = "greywhite", bg = "gray" }
"ui.popup" = { bg = "gray" }
"ui.window" = { fg = "gray" }
"ui.menu" = { fg = "greywhite", bg = "gray" }
"ui.menu.selected" = { fg = "black", bg = "blue" }
"ui.menu.scroll" = { fg = "greywhite", bg = "light-gray" }

# Theme - Code
"namespace" = { fg = "white" }
"module" = { fg = "white" }

"type" = { fg = "AAAclassname" }
"type.enum.variant" = { fg = "light-green" }
# "constructor" = { fg = "orange" }

"keyword" = { fg = "dark-blue" }
"keyword.directive" = { fg = "pink" }
"keyword.control" = { fg = "pink" }
"label" = { fg = "dark-blue" }
"tag" = "dark-blue"

"special" = { fg = "greywhite" }
"operator" = { fg = "white" }

"punctuation" = { fg = "greywhite" }
"punctuation.delimiter" = { fg = "greywhite" }

"variable" = { fg = "white" }
"constant" = { fg = "greywhite" }

"function" = { fg = "function" }
"function.macro" = { fg = "light-red" }
"attribute" = { fg = "light-red" }

"comment" = { fg = "light-gray", modifiers = ["italic"] }

"string" = { fg = "orange" }
"constant.character" = { fg = "orange" }
"constant.character.escape" = { fg = "gold" }

# Theme - Markdown
"markup.heading" = { fg = "white", modifiers = ["bold"] }
"markup.heading.marker" = { fg = "markupmarker" }
"markup.heading.1" = { fg = "red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "dark-blue", modifiers = ["bold"] }
"markup.raw.inline" = { fg = "green" }
"markup.bold" = { fg = "gold", modifiers = ["bold"] }
"markup.italic" = { fg = "purple", modifiers = ["italic"] }
"markup.list" = { fg = "dark-blue" }
"markup.quote" = { fg = "yellow" }
"markup.link.url" = { fg = "light-gray"}
"markup.link.text" = { fg = "dark-blue" }

"diff.plus" = "green"
"diff.delta" = "gold"
"diff.minus" = "red"

diagnostic = { modifiers = ["underlined"] }
"info" = { fg = "blue", modifiers = ["bold"] }
"hint" = { fg = "green", modifiers = ["bold"] }
"warning" = { fg = "yellow", modifiers = ["bold"] }
"error" = { fg = "red", modifiers = ["bold"] }


[palette]
white = "#DCDCDC" # white for code
greywhite = "#ABB2BF" # darker white for UI elements 
gray = "#3E4452"
light-black = "#2C323C"
faint-gray = "#3B4048"
light-gray = "#5C6370"

blue = "#61AFEF"
red = "#E06C75"
light-red = "#E08C95"
purple = "#C678DD"
green = "#98C379"
gold = "#D19A66"
black = "#282C34"
orange = "#ce9178"

# vs colors
dark-blue = "#569CD6"       # Main neutral color used for non-control operators, markdown character etc.
light-blue = "#9CDCFE"      # Currently not used
light-green = "#B5CEA8"     # Used for Enum types
dark-green = "#608B4E"      # Currently no use
pink = "#C586C0"

AAAstring = "#D69D85"
AAAstringinterpolation = "#E3BBAB"
function = "#DCDCAC"
AAAclassname = "#4EC9B0"
AAAtypename = "#569CD6"
AAAinherclassname = "#4EC9B0"
AAAfunctionargandresult = "#70727E"

markupmarker = "#484C54"
